using BlazorApp1.Data;
using BlazorApp1.Data.Seed;
using Microsoft.EntityFrameworkCore;

namespace BlazorApp1.Infrastructure.Database;

public static class AppDatabaseInitializer
{
    public static async Task InitializeDatabaseAsync(this WebApplication app)
    {
        using var scope = app.Services.CreateScope();
        await using var dbContext = await scope.ServiceProvider
            .GetRequiredService<IDbContextFactory<AppDbContext>>()
            .CreateDbContextAsync();

        await dbContext.Database.EnsureCreatedAsync();
        await dbContext.EnsureModuleSchemaAsync();
        await DbSeeder.SeedAsync(dbContext);
    }

    private static async Task EnsureModuleSchemaAsync(this AppDbContext dbContext)
    {
        await dbContext.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "AppModules" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Name" text NOT NULL,
                "Description" text NULL,
                "Image" text NULL,
                "Icon" text NULL,
                "Order" integer NOT NULL DEFAULT 0,
                "IsActive" boolean NOT NULL DEFAULT TRUE,
                "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
                "CreatedBy" text NULL,
                "UpdatedAt" timestamp with time zone NULL,
                "UpdatedBy" text NULL
            );
            """);

        await dbContext.Database.ExecuteSqlRawAsync("""
            INSERT INTO "AppModules" ("Name", "Description", "Icon", "Order", "IsActive", "CreatedAt", "CreatedBy")
            SELECT 'General', 'Default application module', 'bi bi-grid', 1, TRUE, NOW(), 'system'
            WHERE NOT EXISTS (SELECT 1 FROM "AppModules");
            """);

        await dbContext.Database.ExecuteSqlRawAsync("""
            ALTER TABLE "AppMenus"
            ADD COLUMN IF NOT EXISTS "ModuleId" integer NOT NULL DEFAULT 1;
            """);

        await dbContext.Database.ExecuteSqlRawAsync("""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'FK_AppMenus_AppModules_ModuleId'
                ) THEN
                    ALTER TABLE "AppMenus"
                    ADD CONSTRAINT "FK_AppMenus_AppModules_ModuleId"
                    FOREIGN KEY ("ModuleId") REFERENCES "AppModules" ("Id")
                    ON DELETE RESTRICT;
                END IF;
            END $$;
            """);
    }
}
