using BlazorApp1.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace BlazorApp1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260612150000_EnsureEnterpriseSaasTables")]
    public partial class EnsureEnterpriseSaasTables : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "SaasTenants" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "BusinessName" text NOT NULL,
                    "Slug" text NOT NULL,
                    "OwnerName" text NOT NULL,
                    "Email" text NOT NULL,
                    "Phone" text NOT NULL,
                    "IsActive" boolean NOT NULL DEFAULT TRUE,
                    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
                    "UpdatedAt" timestamp with time zone NULL,
                    "CreatedBy" text NULL,
                    "UpdatedBy" text NULL
                );

                CREATE TABLE IF NOT EXISTS "SaasSubscriptionPlans" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "Name" text NOT NULL,
                    "Description" text NOT NULL,
                    "MonthlyPrice" numeric NOT NULL,
                    "UserLimit" integer NOT NULL,
                    "CustomerLimit" integer NOT NULL,
                    "InvoiceLimit" integer NOT NULL,
                    "IsActive" boolean NOT NULL DEFAULT TRUE,
                    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
                    "UpdatedAt" timestamp with time zone NULL,
                    "CreatedBy" text NULL,
                    "UpdatedBy" text NULL
                );

                CREATE TABLE IF NOT EXISTS "SaasTenantSubscriptions" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "TenantId" integer NOT NULL,
                    "SubscriptionPlanId" integer NOT NULL,
                    "StartedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
                    "EndsAt" timestamp with time zone NULL,
                    "Status" text NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
                    "UpdatedAt" timestamp with time zone NULL,
                    "CreatedBy" text NULL,
                    "UpdatedBy" text NULL
                );

                CREATE TABLE IF NOT EXISTS "ServiceItems" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "TenantId" integer NOT NULL,
                    "Name" text NOT NULL,
                    "Category" text NOT NULL,
                    "UnitPrice" numeric NOT NULL,
                    "IsActive" boolean NOT NULL DEFAULT TRUE,
                    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
                    "UpdatedAt" timestamp with time zone NULL,
                    "CreatedBy" text NULL,
                    "UpdatedBy" text NULL
                );

                CREATE TABLE IF NOT EXISTS "WorkOrders" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "TenantId" integer NOT NULL,
                    "CustomerDataId" integer NULL,
                    "OrderNumber" text NOT NULL,
                    "Title" text NOT NULL,
                    "Description" text NOT NULL,
                    "Status" text NOT NULL,
                    "OrderDate" timestamp with time zone NOT NULL DEFAULT NOW(),
                    "DueDate" timestamp with time zone NULL,
                    "EstimatedAmount" numeric NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
                    "UpdatedAt" timestamp with time zone NULL,
                    "CreatedBy" text NULL,
                    "UpdatedBy" text NULL
                );

                CREATE TABLE IF NOT EXISTS "Invoices" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "TenantId" integer NOT NULL,
                    "CustomerDataId" integer NULL,
                    "WorkOrderId" integer NULL,
                    "InvoiceNumber" text NOT NULL,
                    "InvoiceDate" timestamp with time zone NOT NULL DEFAULT NOW(),
                    "DueDate" timestamp with time zone NOT NULL,
                    "Subtotal" numeric NOT NULL,
                    "TaxAmount" numeric NOT NULL,
                    "DiscountAmount" numeric NOT NULL,
                    "TotalAmount" numeric NOT NULL,
                    "PaidAmount" numeric NOT NULL,
                    "Status" text NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
                    "UpdatedAt" timestamp with time zone NULL,
                    "CreatedBy" text NULL,
                    "UpdatedBy" text NULL
                );

                CREATE TABLE IF NOT EXISTS "Payments" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "InvoiceId" integer NOT NULL,
                    "PaidAt" timestamp with time zone NOT NULL DEFAULT NOW(),
                    "Amount" numeric NOT NULL,
                    "Method" text NOT NULL,
                    "ReferenceNumber" text NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
                    "UpdatedAt" timestamp with time zone NULL,
                    "CreatedBy" text NULL,
                    "UpdatedBy" text NULL
                );

                ALTER TABLE "AppUsers" ADD COLUMN IF NOT EXISTS "TenantId" integer NULL;
                ALTER TABLE "CustomerData" ADD COLUMN IF NOT EXISTS "TenantId" integer NULL;

                CREATE UNIQUE INDEX IF NOT EXISTS "IX_SaasTenants_Slug" ON "SaasTenants" ("Slug");
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_SaasSubscriptionPlans_Name" ON "SaasSubscriptionPlans" ("Name");
                CREATE INDEX IF NOT EXISTS "IX_SaasTenantSubscriptions_TenantId" ON "SaasTenantSubscriptions" ("TenantId");
                CREATE INDEX IF NOT EXISTS "IX_SaasTenantSubscriptions_SubscriptionPlanId" ON "SaasTenantSubscriptions" ("SubscriptionPlanId");
                CREATE INDEX IF NOT EXISTS "IX_ServiceItems_TenantId_Name" ON "ServiceItems" ("TenantId", "Name");
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_WorkOrders_TenantId_OrderNumber" ON "WorkOrders" ("TenantId", "OrderNumber");
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_Invoices_TenantId_InvoiceNumber" ON "Invoices" ("TenantId", "InvoiceNumber");
                CREATE INDEX IF NOT EXISTS "IX_Payments_InvoiceId" ON "Payments" ("InvoiceId");
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
        }
    }
}
